# https://grafana.com/docs/grafana/latest/administration/provisioning/#example-dashboard-configuration-file
apiVersion: 1

providers:
  - name: "nest-thermostat"
    type: file
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true
