{
 "title": "Nest Thermostat (F)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "((nest_eco_heat_setpoint_temperature_celsius) * 1.8) + 32",
     "legendFormat": "Eco (Heat)"
    },
    {
     "expr": "((nest_heat_setpoint_temperature_celsius > 0) * 1.8) + 32",
     "legendFormat": "Setpoint (Heat)"
    },
    {
     "expr": "((nest_cool_setpoint_temperature_celsius > 0) * 1.8) + 32",
     "legendFormat": "Setpoint (Cool)"
    },
    {
     "expr": "((nest_eco_cool_setpoint_temperature_celsius) * 1.8) + 32",
     "legendFormat": "Eco (Cool)"
    },
    {
     "expr": "((nest_ambient_temperature_celsius) * 1.8) + 32",
     "legendFormat": "Inside"
    },
    {
     "expr": "((nest_weather_temperature_celsius) * 1.8) + 32",
     "legendFormat": "Outside"
    }
   ]
  },
  {
   "title": "Humidity and Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nest_humidity_percent", "legendFormat": "Inside Humidity" },
    { "expr": "nest_weather_humidity_percent", "legendFormat": "Outside Humidity" },
    {
     "expr": "nest_weather_pressure_hectopascal",
     "legendFormat": "Outside Pressure"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((nest_ambient_temperature_celsius) * 1.8) + 32",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "(sum without(mode) (nest_status{mode=\"COOLING\"}*-1)) or (sum without(mode) (nest_status{mode=\"OFF\"}*0)) or (sum without(mode) (nest_status{mode=\"HEATING\"}*2))",
     "legendFormat": "Status: {{mode}}"
    },
    {
     "expr": "(sum without(mode) (nest_mode{mode=\"COOL\"}*-1)) or (sum without(mode) (nest_mode{mode=\"OFF\"}*0)) or (sum without(mode) (nest_mode{mode=\"HEAT\"}*2)) or (sum without(mode) (nest_mode{mode=\"HEATCOOL\"}*3))",
     "legendFormat": "Mode"
    },
    {
     "expr": "(sum without(mode) (nest_eco_mode{mode=\"OFF\"}*0)) or (sum without(mode) (nest_eco_mode{mode!=\"OFF\"}*1))",
     "legendFormat": "Eco Mode"
    },
    {
     "expr": "(sum without(mode) (nest_fan_timer_mode{mode=\"OFF\"}*0)) or (sum without(mode) (nest_fan_timer_mode{mode!=\"OFF\"}*1))",
     "legendFormat": "Fan"
    }
   ]
  }
 ]
}