services:
  prometheus:
    # https://dhi.io/catalog/prometheus
    image: dhi.io/prometheus:3.15
    ports:
      - "9090:9090"
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-volume:/var/prometheus

  grafana:
    # https://dhi.io/catalog/grafana
    image: dhi.io/grafana:13
    ports:
      - "3000:3000"
    volumes:
      - ./files/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./files/grafana-providers.yml:/etc/grafana/provisioning/dashboards/providers.yml
      - ./files/dashboards/nest-thermostat.json:/var/lib/grafana/dashboards/pronestheus/nest-thermostat.json
      - ./files/dashboards/nest-thermostat-fahrenheit.json:/var/lib/grafana/dashboards/pronestheus/nest-thermostat-fahrenheit.json
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      # - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/pronestheus/nest-thermostat.json

  pronestheus:
    # https://hub.docker.com/r/dandw/pronestheus/tags
    image: dandw/pronestheus:latest
    ports:
      - "9777:9777"
    environment:
      - PRONESTHEUS_NEST_CLIENT_ID_FILE=/run/secrets/pronestheus_nest_client_id
      - PRONESTHEUS_NEST_CLIENT_SECRET_FILE=/run/secrets/pronestheus_nest_client_secret
      - PRONESTHEUS_NEST_PROJECT_ID_FILE=/run/secrets/pronestheus_nest_project_id
      - PRONESTHEUS_NEST_REFRESH_TOKEN_FILE=/run/secrets/pronestheus_nest_refresh_token
      - PRONESTHEUS_OWM_AUTH_FILE=/run/secrets/pronestheus_owm_auth
      - PRONESTHEUS_OWM_LOCATION_FILE=/run/secrets/pronestheus_owm_location
    secrets:
      - pronestheus_nest_client_id
      - pronestheus_nest_client_secret
      - pronestheus_nest_project_id
      - pronestheus_nest_refresh_token
      - pronestheus_owm_auth
      - pronestheus_owm_location

secrets:
  pronestheus_nest_client_id:
    file: ${HOME}/.secrets/pronestheus_nest_client_id
  pronestheus_nest_client_secret:
    file: ${HOME}/.secrets/pronestheus_nest_client_secret
  pronestheus_nest_project_id:
    file: ${HOME}/.secrets/pronestheus_nest_project_id
  pronestheus_nest_refresh_token:
    file: ${HOME}/.secrets/pronestheus_nest_refresh_token
  pronestheus_owm_auth:
    file: ${HOME}/.secrets/pronestheus_owm_auth
  pronestheus_owm_location:
    file: ${HOME}/.secrets/pronestheus_owm_location

volumes:
  prometheus-data-volume:
